//! The `ops.bin` seed-7 fixture: 5,000 concrete ops generated by `SplitMix64(7)` through the
//! shared interpreter (in-range 2,048-tick window, base 10000, mid 11024, drift +7 every 500
//! ops, 5 % unknown ids), committed as `tests/fixtures/ops_seed7.bin` so the Python reference
//! model can replay the identical stream. Pinned: sha256 of the file, the event-log digest,
//! the close book-state hash, the error count and the live-order count.
//!
//! The research report's seed-1/2/3 digests come from Python's `random.Random` and are NOT
//! reproduced here (docs/PLAN.md: "fed by a dumped ops.bin, never by porting Python's RNG");
//! a Python dump replayed through `lob_core::replay` is the way to compare them.
//!
//! Regenerate with `LOB_CORE_WRITE_FIXTURES=1 cargo test -p lob-core --test ops_seed7`.
//! `tests/fixtures/ops_pyref.py` is the stdlib-only Python reference that reproduces the pins.

mod common;

use std::path::Path;

use common::{Interp, SplitMix64};
use lob_core::{
    ArrayBook, BookConfig, EventLog, Op, OrderBook, RefBook, decode_ops, encode_ops, hex, replay,
};
use sha2::{Digest, Sha256};

const N_OPS: usize = 5_000;
const FIXTURE: &[u8] = include_bytes!("fixtures/ops_seed7.bin");

// The four pins below were reproduced by an independent pure-Python dict+deque reference
// (hashlib) replaying the same ops.bin: digest, close hash, 358 errors, 999 live orders.
const OPS_BIN_SHA256: &str = "1fa8bb02c4742810f688448c475fabda0939184524c8caa256a5504b31bdc2a7";
const EVENT_LOG_DIGEST: &str = "824b07d9f1020144f03f565796c9ca50d76954faa58b0234843183d0874f81f9";
const CLOSE_STATE_HASH: &str = "0ac37ba1f591ce1e020d20b6d9ce9a62bb35ac296653c9ea6b2ad050f741ecd2";
const N_ERRORS: usize = 358;
const N_LIVE: usize = 999;

fn cfg() -> BookConfig {
    BookConfig::new(10_000, 2048, 1)
}

fn generate() -> Vec<Op> {
    let mut rng = SplitMix64(7);
    let mut reference = RefBook::new();
    let mut interp = Interp::new(11_024, 7, Some((10_000, 12_047)));
    (0..N_OPS)
        .map(|_| {
            let op = interp.resolve(rng.abs_op(), reference.l1());
            interp.observe(&op.apply(&mut reference));
            op
        })
        .collect()
}

#[test]
fn seed7_fixture_matches_the_generator() {
    let bytes = encode_ops(&generate());
    if std::env::var_os("LOB_CORE_WRITE_FIXTURES").is_some() {
        let path = Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/ops_seed7.bin");
        std::fs::write(&path, &bytes).unwrap();
        eprintln!("wrote {} ({} bytes)", path.display(), bytes.len());
    }
    assert_eq!(bytes.len(), N_OPS * lob_core::ops::OP_RECORD_LEN);
    assert_eq!(
        bytes, FIXTURE,
        "committed ops_seed7.bin differs from the generator"
    );
    let digest: [u8; 32] = Sha256::digest(&bytes).into();
    assert_eq!(hex(&digest), OPS_BIN_SHA256);
}

#[test]
fn seed7_replay_pins_event_log_and_state_hash_on_both_books() {
    let ops = decode_ops(FIXTURE).unwrap();
    assert_eq!(ops.len(), N_OPS);
    let mut array = ArrayBook::with_capacity(cfg(), 4096);
    let mut reference = RefBook::new();
    let mut log_a = EventLog::new();
    let mut log_r = EventLog::new();
    let errs_a = replay(&mut array, &ops, &mut log_a);
    let errs_r = replay(&mut reference, &ops, &mut log_r);
    assert_eq!(errs_a, errs_r);
    assert_eq!(log_a.len(), N_OPS as u64);
    assert_eq!(log_a.digest(), log_r.digest());
    assert_eq!(array.state_hash(), reference.state_hash());
    assert_eq!(array.snapshot(), reference.snapshot());
    array.check().unwrap();
    assert_eq!(
        array.overflow_hits(),
        0,
        "the seed-7 stream is in-range by construction"
    );
    assert_eq!(
        (
            hex(&log_a.digest()),
            hex(&array.state_hash()),
            errs_a,
            array.live_orders()
        ),
        (
            EVENT_LOG_DIGEST.to_string(),
            CLOSE_STATE_HASH.to_string(),
            N_ERRORS,
            N_LIVE
        )
    );
}
